### ISSUE TITLE
Will we have space/time to add a few multiple-choice questions for volunteers about their patients?

### ISSUE THREAD

**Issue by db626** [FACG5/Twig#105]
Will we have space/time to add a few multiple-choice questions for volunteers about their patients?

I could make them simple. Mostly about their patients nutrition, vaccine history, attitudes towards prescription drugs...

Let me know.

**Comment by FarahZaqout** [comment]
Of course we will have time for that! 
We have more than 3 weeks. We almost finished the views from Figma, and I expect that we will be able to work on more website pages/features than what we showed you. 

I think we will be able to give you a live link tomorrow at most. (I am hoping to be able to do that today). 

Of course, your feedback on the current work after we provide you with a live link should take priority unless otherwise you require, but even with that, we still expect to plan and finish more tasks than what we currently have. 

I am hoping I can get you and the rest of the team to have a video hangout sometime next week where we can review progress, go through the live website together and perhaps discuss the work going forward as well as any concerns/thoughts you might have.

Let me know if you prefer a date, and time.
