### ISSUE TITLE
Aaaah! Languages, dialects. Nightmare.

### ISSUE THREAD

**Issue by db626** [FACG5/Twig#175]
Ok. We are going to forget the Language/Dialect distinction.

We are going to put all 7,000+ languages on Ethnologue in a 'languages' category. Do not split them.
I'm sending a screenshot of Arabic. This means that Arabic, Omani Spoken' would just be a single language. (NOT NOT NOT Language: 'Arabic', Dialect, 'Omani Spoken'.) The reason is this: It turns out that if you click on "Arabic, Omani Spoken", ETHNOLOGUE GIVES YOU EVEN MORE DIALECTS OF THIS LANGUAGE.

https://www.ethnologue.com/browse/names/a

For the purposes of testing we can just include the 'Arabics" on this list, for example. But in reality we need to figure out a way a computer can deal with this problem. Like, how are we going to figure out a way to ask a 'Arabic, Omani Spoken' speaker if he/she's alright with verifying 'Arabic, Najdi spoken'.

WHAT WE NEED NOW:

The languages that test users would possibly speak (All the Arabics, all the Portugeses, American Sign Language, all the Russians, all the Indian languages).

I don't know how you're going to put 7000 languages in a dropdown tab. 

IN THE FUTURE:

Maybe we can do

- Language tab (7,000 languages)
- Notes (the user types in something freeform, like if they're Spanish they type in "Mexico" or something)
- The user goes through the list of 7,000 languages at some point and ticks off which he/she feels comfortable verifying (not translating).

Sorry. This is a big problem to overcome. I just can't (can't!) divide a list of 7,000 into even smaller pieces. It's also a challenge for a programmer to figure out how to make it 'navigateable' for a user. This is yet another reason why latitude and longitude is important- more important to know where the volunteer translator is from than the linguistic names for these.

![arabicatethnologue](https://user-images.githubusercontent.com/44851386/48801319-f1aafd80-ed03-11e8-9c9f-b7d10cd3fc7f.jpg)

**Comment by db626** [comment]
Correction: 

The languages that test users would possibly speak (All the Arabics, all the Portugeses, American Sign Language, all the Russians, all the Indian languages).

I forgot all the Nigerian languages. We need Nigerian languages.

**Comment by FarahZaqout** [comment]
This might call for a redesign of the registration process. I will discuss it with the team and see which is most feasible and sustainable on the long run, in terms of user experience.

My initial thought is not to put everything in a dropdown list, but to have a fully fledged registration process rather than a pop-up modal.

This way we can have an entire page dedicated to the languages, while maintaining clear instructions and avoid overwhelming the user. 

The team might have a better solution, however, in any case, I will start thinking of possible designs so by the time initial testing concludes I can just discuss potential mock-ups with you and the team and agree on a suitable one as soon as possible if it turns out that we have to redesign the registration process.

But for now, I think it's best to stick with the drop down list in order to get something testable in time.
